# Generated by Django 4.2.4 on 2023-09-01 22:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_rename_user_id_order_customer_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("customer", "order_item")},
        ),
    ]
