# Generated by Django 4.2.4 on 2023-09-01 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0004_alter_book_quantity_alter_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("customer", "status")},
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CART")),
                fields=("customer", "status"),
                name="unique_cart_per_customer",
            ),
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_item",
        ),
    ]
