# Generated by Django 4.2.4 on 2023-09-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_order_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="order_item",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.order"
            ),
            preserve_default=False,
        ),
    ]
