# Generated by Django 4.2.4 on 2023-09-01 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_order_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="order_item",
            new_name="order",
        ),
    ]
